### ISSUE TITLE
Path to docker-compose file in project source

### ISSUE THREAD

**Issue by saitho** [mackerelserver/deployment#1]
Instead of specifying the services in the project configuration it should also be possible to specify an existing docker-compose file that is already used in the project source.

Example:
```yaml
deployment:
  type: docker
  service_file: ../../docker-compose.yml # relative path from the project configuration file
```
Mutually exclusive with `services` setting.

It will then extract the information that can currently be set in project configuration from that file.
